language: node_js
jdk:
  - oraclejdk8
node_js:
  - "lts/*"
install:
  - npm install
  - npm run compile
cache:
  directories:
  - $HOME/.m2
  - ./node_modules
script:
  - ./test.sh
after_success:
  - ./node_modules/.bin/codecov
